# Define list of POS that will be used for regexes
spacy_pos = {
 'ADJ'  : 'adjective',
 'ADP'  : 'adposition',
 'ADV'  : 'adverb',
 'AUX'  : 'auxiliary verb',
 'CONJ' : 'coordinating conjunction',
 'DET'  : 'determiner',
 'INTJ' : 'interjection',
 'NOUN' : 'noun',
 'NUM'  : 'numeral',
 'PART' : 'particle',
 'PRON' : 'pronoun',
 'PROPN': 'proper noun',
 'PUNCT': 'punctuation',
 'SCONJ': 'subordinating conjunction',
 'SYM'  : 'symbol',
 'VERB' : 'verb',
 'X'    : 'other'
 }



NLTK_pos = {
'CC'  : 'Coordinating conjunction',
'CD'  : 'Cardinal number'  ,
'DT'  : 'Determiner'  ,
'EX'  : 'Existential there'  ,
'FW'  : 'Foreign word',  
'IN'  : 'Preposition or subordinating conjunction',  
'JJ'  : 'Adjective',  
'JJR' : 'Adjective, comparative',  
'JJS' : 'Adjective, superlative',  
'LS'  : 'List item marker',  
'MD'  : 'Modal',  
'NN'  : 'Noun, singular or mass',
'NNS' : 'Noun, plural',  
'NNP' : 'Proper noun, singular',  
'NNPS': 'Proper noun, plural',  
'PDT' : 'Predeterminer',  
'POS' : 'Possessive ending',  
'PRP' : 'Personal pronoun',  
'PRP$': 'Possessive pronoun',  
'RB'  : 'Adverb',  
'RBR' : 'Adverb, comparative',  
'RBS' : 'Adverb, superlative',  
'RP'  : 'Particle', 
'SYM' : 'Symbol',  
'TO'  : 'to',  
'UH'  : 'Interjection',  
'VB'  : 'Verb, base form' , 
'VBD' : 'Verb, past tense',
'VBG' : 'Verb, gerund or present participle',  
'VBN' : 'Verb, past participle',  
'VBP' : 'Verb, non-3rd person singular present',  
'VBZ' : 'Verb, 3rd person singular present',  
'WDT' : 'Wh-determiner',  
'WP'  : 'Wh-pronoun',  
'WP$' : 'Possessive wh-pronoun',  
'WRB' : 'Wh-adverb', 
}


source_pos = {
'adj.'       : 'adjetivo',
'adv.'       : 'adverbio',
'anim.'      : 'animado',
'Antón.'     : 'antónimo',
'art.'       : 'artículo',
'compl.'     : 'complemento',
'conj.'      : 'conjunción',
'f.'         : 'femenino',
'fem.'       : 'femenino',
'fut.'       : 'futuro',
'inan.'      : 'inanimado',
'interj.'    : 'interjección',
'm.'         : 'masculino',
'masc.'      : 'masculino',
'pas.'       : 'pasado',
'pl.'        : 'plural',
'posp.'      : 'posposición',
'pref. sust.': 'sust. prefijo sustantival',
'pref. verb.': 'verb. prefijo verbal',
'prep.'      : 'preposición',
'pres.'      : 'presente',
'pron.'      : 'pronombre',
's.f.'       : 'sustantivo femenino',
'sing.'      : 'singular',
'Sinón.'     : 'sinónimo',
's.m.'       : 'sustantivo masculino',
's.n.'       : 'sustantivo neutro',
'suf. sust.' : 'sust. sufijo sustantival',
'suf. verb.' : 'verb. sufijo verbal',
'suj.'       : 'sujeto',
'var.'       : 'variante de pronunciación',
'v.e.'       : 'verbo de estado',
'v.i.'       : 'verbo intransitivo',
'v. recíp.'  : 'verbo recíproco',
'v. refl.'   : 'verbo reflexivo',
'v.t.'       : 'verbo transitivo'
}
